"""Obsidian export and Claude compatibility helpers."""

from __future__ import annotations

import re
from pathlib import Path

from vorbit_core.config import VorbitConfig
from vorbit_core.learn.models import CaptureRecord, ReviewItem
from vorbit_core.learn.storage import LearnStore


def _obsidian_agent_dir(config: VorbitConfig, agent: str) -> Path:
    """Return the Obsidian vault subdirectory for a given agent."""
    assert config.obsidian.vault_path is not None
    return config.obsidian.vault_path / agent


def ensure_dataview_index(config: VorbitConfig, agent: str) -> None:
    """Ensure a Dataview-based corrections index exists for this agent."""
    if config.obsidian.vault_path is None:
        return
    agent_dir = _obsidian_agent_dir(config, agent)
    index_path = agent_dir / "_corrections-index.md"
    if index_path.exists():
        return
    index_path.parent.mkdir(parents=True, exist_ok=True)
    (agent_dir / "universal").mkdir(parents=True, exist_ok=True)
    index_path.write_text(
        "# Corrections Index\n\n"
        f"Auto-generated by vorbit learn ({agent}). Live query via Dataview.\n\n"
        "```dataview\n"
        "TABLE date, project, capture_type as Type, status, rule\n"
        f'FROM "{agent}/projects" OR "{agent}/universal"\n'
        "WHERE capture_type\n"
        "SORT date DESC\n"
        "```\n"
    )


def setup_claude_rules_symlink(rules_source: Path) -> None:
    """Claude-only: symlink vorbit-learning-rules.md into ~/.claude/rules/."""
    rules_dir = Path.home() / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    rules_file = rules_dir / "vorbit-learning.md"
    marker = "vorbit-learning-rules"
    try:
        content = rules_file.read_text() if rules_file.exists() else ""
    except OSError:
        content = ""
    if marker in content:
        return
    if rules_file.exists() or rules_file.is_symlink():
        rules_file.unlink()
    rules_file.symlink_to(rules_source)


def _frontmatter_date(timestamp: str) -> str:
    return timestamp.split("T", 1)[0]


def write_obsidian_note(config: VorbitConfig, capture: CaptureRecord) -> str:
    """Write correction note to the agent's Obsidian subfolder. Returns relative path within vault."""
    agent_dir = _obsidian_agent_dir(config, capture.source_agent)
    note_dir = agent_dir / "projects" / capture.project_name
    note_dir.mkdir(parents=True, exist_ok=True)

    first_msg = capture.user_messages[0] if capture.user_messages else capture.capture_type
    slug = re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", first_msg.lower())).strip("-") or "correction"
    date_str = _frontmatter_date(capture.created_at)
    filename = f"{date_str}-{slug}.md"
    note_path = note_dir / filename
    counter = 1
    while note_path.exists():
        filename = f"{date_str}-{slug}-{counter}.md"
        note_path = note_dir / filename
        counter += 1

    note_content = f"""---
date: {date_str}
project: {capture.project_name}
project_path: {capture.project_root}
capture_type: {capture.capture_type}
source_agent: {capture.source_agent}
root_cause: ""
status: pending
rule: ""
routed_to: ""
tags: [{capture.project_name}, {capture.source_agent}]
---

# {first_msg[:100].strip()}

## Conversation Context

**User said:**
{capture.context.problem}

**What agent did before correction:**
{capture.context.before or "_No preceding context._"}

**What agent found after correction:**
{capture.context.diagnosis or "_No diagnosis captured._"}

**How agent fixed it:**
{capture.context.resolution or "_No fix captured._"}

## Root Cause Analysis
_Agent: analyze the context above. Proposed scope is {capture.metadata.get("proposed_scope", "pending review")}._

## Suggested Rule
_Agent: draft the durable rule after review._

## Destination
_Agent: route this into the canonical Vorbit rules store after review._

## Raw Transcript
{capture.context.full_context}
"""
    note_path.write_text(note_content)
    return str(note_path.relative_to(config.obsidian.vault_path))


def write_claude_pending_bridge(config: VorbitConfig, review_item: ReviewItem, obsidian_relpath: str) -> Path:
    """Claude-only: write pending-capture.md bridge + symlink into ~/.claude/rules/."""
    claude_rules_dir = Path.home() / ".claude" / "rules"
    claude_rules_dir.mkdir(parents=True, exist_ok=True)
    claude_dir = _obsidian_agent_dir(config, "claude")
    source_path = claude_dir / "pending-capture.md"
    timestamp = review_item.created_at[:10]
    full_note_path = str(config.obsidian.vault_path / obsidian_relpath) if config.obsidian.vault_path else obsidian_relpath
    block = (
        f"## [VORBIT:{review_item.capture_type.upper()}-CAPTURE] | Project: {review_item.project_root} | {timestamp}\n"
        f"Source agent: {review_item.source_agent}\n"
        f"Canonical review id: {review_item.id}\n"
        f"Full context saved to Obsidian: {obsidian_relpath}\n"
        f"Read the note at {full_note_path} for rich context before classifying.\n\n"
        "---\n\n"
    )
    if not source_path.exists():
        source_path.parent.mkdir(parents=True, exist_ok=True)
        source_path.write_text(
            "# Pending Captures\n\n"
            "**Action required:** Review the linked notes, then approve or reject via Vorbit review flow.\n\n"
            "---\n\n"
        )
    with open(source_path, "a") as handle:
        handle.write(block)
    link_path = claude_rules_dir / "pending-capture.md"
    if not link_path.exists() and not link_path.is_symlink():
        link_path.symlink_to(source_path)
    return source_path


def sync_obsidian_export(
    store: LearnStore,
    config: VorbitConfig,
    capture: CaptureRecord,
    review_item: ReviewItem,
) -> str | None:
    """Write Obsidian note for any agent. Claude also gets the pending-capture.md bridge."""
    if not config.obsidian.enabled or config.obsidian.vault_path is None:
        return None
    ensure_dataview_index(config, capture.source_agent)
    obsidian_relpath = write_obsidian_note(config, capture)
    if config.legacy_claude_bridge:
        write_claude_pending_bridge(config, review_item, obsidian_relpath)
    return obsidian_relpath
